spring:
  # Profile
  application:
    name: SeafoodWholesaler_OMS
  profiles:
    active: prod
  config:
    # Below path is for Render cloud deployment
    import: optional:file:/etc/secrets/config.env[.properties]