spring:
  # DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/nsy?serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # SpringMail
  mail: 
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  # SessionFactory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        # implicit-strategy 負責模型對象層次的處理，將對像模型處理為邏輯名稱，當沒有使用@Table和@Column註解時，implicit-strategy配置項才會被使用，當對像模型中已經指定時，implicit-strategy並不會起作用。
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        # physical-strategy 負責映射成真實的數據名稱的處理，將上述的邏輯名稱處理為物理名稱，physical-strategy一定會被應用，與對像模型中是否顯式地指定列名或者已經被隱式決定無關。
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # ViewResolver
  #  mvc:
  #    view:
  #       prefix: /WEB-INF/views
  #       suffix: .jsp
jwt:
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
server:
  servlet:
    context-path: